import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ポートフォリオ（仮）</title>
        <a>sssss</a>
        <p>いいね数</p>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>プロフィール</p>
        <p>名前（API）</p>
        <p>肩書き（API）</p>
        <p>説明文（API）</p>
        <p>作品一覧（API→mapで全部出す）</p>
      </main>

      <footer className={styles.footer}>
        <p>aaaa</p>
      </footer>
    </div>
  )
}

export default Home
